industry_to_etf = {
    "Advertising Agencies": "XLC",
    "Aerospace & Defense": "ITA",
    "Agricultural Inputs": "MOO",
    "Airlines": "JETS",
    "Airports & Air Services": "SEA",
    "Aluminum": "JJU",
    "Apparel Manufacturing": "XRT",
    "Apparel Retail": "XRT",
    "Asset Management": "KIE",
    "Auto & Truck Dealerships": "CARZ",
    "Auto Manufacturers": "CARZ",
    "Auto Parts": "CARZ",
    "Banks - Diversified": "KBE",
    "Banks - Regional": "KRE",
    "Beverages - Brewers": "PBJ",
    "Beverages - Non-Alcoholic": "PBJ",
    "Beverages - Wineries & Distilleries": "PBJ",
    "Biotechnology": "XBI",
    "Broadcasting": "XLC",
    "Building Materials": "XLB",
    "Building Products & Equipment": "XLI",
    "Business Equipment & Supplies": "XLI",
    "Capital Markets": "KCE",
    "Chemicals": "XLB",
    "Coking Coal": "KOL",
    "Communication Equipment": "XLC",
    "Computer Hardware": "IYW",
    "Confectioners": "PBJ",
    "Conglomerates": "XLI",
    "Consulting Services": "XLI",
    "Consumer Electronics": "IYW",
    "Copper": "COPX",
    "Credit Services": "KIE",
    "Department Stores": "XRT",
    "Diagnostics & Research": "XHE",
    "Discount Stores": "XRT",
    "Drug Manufacturers - General": "IHE",
    "Drug Manufacturers - Specialty & Generic": "IHE",
    "Education & Training Services": "EDUT",
    "Electrical Equipment & Parts": "XLI",
    "Electronic Components": "SOXX",
    "Electronic Gaming & Multimedia": "ESPO",
    "Electronics & Computer Distribution": "IYW",
    "Engineering & Construction": "XLI",
    "Entertainment": "XLC",
    "Farm & Heavy Construction Machinery": "MOO",
    "Farm Products": "MOO",
    "Financial Conglomerates": "XLF",
    "Financial Data & Stock Exchanges": "KCE",
    "Food Distribution": "PBJ",
    "Footwear & Accessories": "XRT",
    "Furnishings, Fixtures & Appliances": "XHB",
    "Gambling": "BETZ",
    "Gold": "GLD",
    "Grocery Stores": "KXI",
    "Health Information Services": "XLV",
    "Healthcare Plans": "XLV",
    "Home Improvement Retail": "XHB",
    "Household & Personal Products": "XLP",
    "Industrial Distribution": "XLI",
    "Information Technology Services": "IYW",
    "Infrastructure Operations": "PAVE",
    "Insurance - Diversified": "KIE",
    "Insurance - Life": "KIE",
    "Insurance - Property & Casualty": "KIE",
    "Insurance - Reinsurance": "KIE",
    "Insurance - Specialty": "KIE",
    "Insurance Brokers": "KIE",
    "Integrated Freight & Logistics": "IYT",
    "Internet Content & Information": "FDN",
    "Internet Retail": "IBUY",
    "Leisure": "PEJ",
    "Lodging": "PEJ",
    "Lumber & Wood Production": "WOOD",
    "Luxury Goods": "LUXE",
    "Marine Shipping": "SEA",
    "Medical Care Facilities": "XLV",
    "Medical Devices": "IHI",
    "Medical Distribution": "IHI",
    "Medical Instruments & Supplies": "IHI",
    "Metal Fabrication": "XME",
    "Mortgage Finance": "REM",
    "Oil & Gas Drilling": "XOP",
    "Oil & Gas E&P": "XOP",
    "Oil & Gas Equipment & Services": "XES",
    "Oil & Gas Integrated": "XLE",
    "Oil & Gas Midstream": "AMLP",
    "Oil & Gas Refining & Marketing": "CRAK",
    "Other Industrial Metals & Mining": "XME",
    "Other Precious Metals & Mining": "GDX",
    "Packaged Foods": "PBJ",
    "Packaging & Containers": "XLP",
    "Paper & Paper Products": "WOOD",
    "Personal Services": "XLY",
    "Pharmaceutical Retailers": "XLP",
    "Pollution & Treatment Controls": "PAVE",
    "Publishing": "XLC",
    "Railroads": "IYT",
    "Real Estate - Development": "XLRE",
    "Real Estate - Diversified": "XLRE",
    "Real Estate Services": "XLRE",
    "Recreational Vehicles": "XLY",
    "REIT - Diversified": "VNQ",
    "REIT - Healthcare Facilities": "XLRE",
    "REIT - Hotel & Motel": "PEJ",
    "REIT - Industrial": "VNQ",
    "REIT - Mortgage": "REM",
    "REIT - Office": "VNQ",
    "REIT - Residential": "REZ",
    "REIT - Retail": "RWR",
    "REIT - Specialty": "XLRE",
    "Rental & Leasing Services": "XLI",
    "Residential Construction": "XHB",
    "Resorts & Casinos": "PEJ",
    "Restaurants": "BITE",
    "Scientific & Technical Instruments": "IYW",
    "Security & Protection Services": "XLI",
    "Semiconductor Equipment & Materials": "SOXX",
    "Semiconductors": "SOXX",
    "Shell Companies": "SPAC",
    "Silver": "SLV",
    "Software - Application": "IGV",
    "Software - Infrastructure": "IGV",
    "Solar": "TAN",
    "Specialty Business Services": "XLI",
    "Specialty Chemicals": "XLB",
    "Specialty Industrial Machinery": "XLI",
    "Specialty Retail": "XRT",
    "Staffing & Employment Services": "XLI",
    "Steel": "SLX",
    "Telecom Services": "IYZ",
    "Textile Manufacturing": "XRT",
    "Thermal Coal": "KOL",
    "Tobacco": "XLP",
    "Tools & Accessories": "XLI",
    "Travel Services": "AWAY",
    "Trucking": "IYT",
    "Uranium": "URA",
    "Utilities - Diversified": "XLU",
    "Utilities - Independent Power Producers": "XLU",
    "Utilities - Regulated Electric": "XLU",
    "Utilities - Regulated Gas": "XLU",
    "Utilities - Regulated Water": "FIW",
    "Utilities - Renewable": "ICLN",
    "Waste Management": "PAVE"
}
